<?php
/*
 * BandwidthMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthMessagingLib\Exceptions;

use BandwidthMessagingLib\APIException;
use BandwidthMessagingLib\APIHelper;

/**
 * 404 Not Found
 */
class BandwidthNotFoundException extends APIException
{
    /**
     * @todo Write general description for this property
     * @var string|null $timestamp public property
     */
    public $timestamp;

    /**
     * @todo Write general description for this property
     * @var string|null $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @var string|null $error public property
     */
    public $error;

    /**
     * @todo Write general description for this property
     * @var string|null $message public property
     */
    public $message;

    /**
     * @todo Write general description for this property
     * @var string|null $path public property
     */
    public $path;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
