<?php
/*
 * BandwidthMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BandwidthMessagingLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://messaging.bandwidth.com/api/v2';

    /**
     * user
     * @var string
     */
    public static $user = '';

    /**
     * pass
     * @var string
     */
    public static $pass = '';
}
